<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Credit Note {{ $creditNote->credit_note_number }}</title>
    <style>
        body { font-family: sans-serif; font-size: 10px; color: #333; line-height: 1.4; margin: 0; padding: 15px; }
        table { width: 100%; border-collapse: collapse; }
        .detail-table td { padding: 4px 8px; font-size: 10px; border-bottom: 1px solid #eee; }
        .detail-table .label { width: 140px; color: #666; font-weight: bold; }
        .credit-box { background: #dc3545; color: #fff; text-align: center; padding: 15px; margin: 15px 0; border-radius: 4px; }
        .credit-box h2 { margin: 0; font-size: 24px; }
        .credit-box p { margin: 5px 0 0 0; font-size: 10px; }
        .footer { margin-top: 20px; font-size: 8px; color: #888; text-align: center; border-top: 1px solid #ddd; padding-top: 10px; }
    </style>
</head>
<body>
    @include('frontdeskcrm::pdf._letterhead', [
        'docTitle' => 'CREDIT NOTE',
        'docNumber' => $creditNote->credit_note_number,
        'docDate' => $creditNote->issue_date?->format('M d, Y') ?? now()->format('M d, Y'),
    ])

    <div class="credit-box">
        <p>Credit Amount</p>
        <h2>{{ $creditNote->invoice->currency ?? 'NGN' }} {{ number_format($creditNote->amount, 2) }}</h2>
    </div>

    <table class="detail-table" style="width: 100%; margin-bottom: 15px;">
        <tr>
            <td class="label">Credit Note #:</td>
            <td><strong>{{ $creditNote->credit_note_number }}</strong></td>
            <td class="label">Issue Date:</td>
            <td>{{ $creditNote->issue_date?->format('M d, Y') ?? 'N/A' }}</td>
        </tr>
        <tr>
            <td class="label">Original Invoice:</td>
            <td>{{ $creditNote->invoice->invoice_number ?? 'N/A' }}</td>
            <td class="label">Invoice Total:</td>
            <td>{{ number_format($creditNote->invoice->total ?? 0, 2) }}</td>
        </tr>
        <tr>
            <td class="label">Guest Name:</td>
            <td>{{ $creditNote->invoice->registration->full_name ?? 'N/A' }}</td>
            <td class="label">Registration:</td>
            <td>#{{ $creditNote->invoice->registration_id ?? 'N/A' }}</td>
        </tr>
        <tr>
            <td class="label">Created By:</td>
            <td>{{ $creditNote->createdBy->name ?? 'System' }}</td>
            <td class="label"></td>
            <td></td>
        </tr>
    </table>

    <div style="margin-bottom: 15px; padding: 8px; background: #fff3cd; border-left: 3px solid #ffc107;">
        <strong style="font-size: 9px;">Reason for Credit Note:</strong>
        <p style="margin: 3px 0; font-size: 10px; color: #333;">{{ $creditNote->reason }}</p>
    </div>

    @if($creditNote->notes)
    <div style="margin-bottom: 15px; padding: 8px; background: #f8f9fa; border-left: 3px solid #6c757d;">
        <strong style="font-size: 9px;">Additional Notes:</strong>
        <p style="margin: 3px 0; font-size: 9px; color: #555;">{{ $creditNote->notes }}</p>
    </div>
    @endif

    <div class="footer">
        <p style="margin: 0;">This credit note has been applied to the referenced invoice.</p>
        <p style="margin: 2px 0 0 0;">Generated by Brickspoint HMS on {{ now()->format('M d, Y H:i A') }}</p>
    </div>
</body>
</html>
