<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Receipt {{ $receipt->receipt_number }}</title>
    <style>
        body { font-family: sans-serif; font-size: 10px; color: #333; line-height: 1.4; margin: 0; padding: 15px; }
        table { width: 100%; border-collapse: collapse; }
        .detail-table td { padding: 4px 8px; font-size: 10px; border-bottom: 1px solid #eee; }
        .detail-table .label { width: 140px; color: #666; font-weight: bold; }
        .amount-box { background: #28a745; color: #fff; text-align: center; padding: 15px; margin: 15px 0; border-radius: 4px; }
        .amount-box h2 { margin: 0; font-size: 24px; }
        .amount-box p { margin: 5px 0 0 0; font-size: 10px; }
        .footer { margin-top: 20px; font-size: 8px; color: #888; text-align: center; border-top: 1px solid #ddd; padding-top: 10px; }
    </style>
</head>
<body>
    @include('frontdeskcrm::pdf._letterhead', [
        'docTitle' => 'PAYMENT RECEIPT',
        'docNumber' => $receipt->receipt_number,
        'docDate' => $receipt->receipted_at?->format('M d, Y H:i') ?? now()->format('M d, Y H:i'),
    ])

    <div class="amount-box">
        <p>Amount Received</p>
        <h2>{{ $receipt->payment->registration->currency ?? 'NGN' }} {{ number_format($receipt->amount, 2) }}</h2>
    </div>

    <table class="detail-table" style="width: 100%; margin-bottom: 15px;">
        <tr>
            <td class="label">Receipt Number:</td>
            <td><strong>{{ $receipt->receipt_number }}</strong></td>
            <td class="label">Payment Method:</td>
            <td>{{ ucfirst($receipt->payment_method) }}</td>
        </tr>
        <tr>
            <td class="label">Date & Time:</td>
            <td>{{ $receipt->receipted_at?->format('M d, Y H:i A') ?? 'N/A' }}</td>
            <td class="label">Reference:</td>
            <td>{{ $receipt->payment->reference ?? 'N/A' }}</td>
        </tr>
        <tr>
            <td class="label">Guest Name:</td>
            <td>{{ $receipt->payment->registration->full_name ?? 'N/A' }}</td>
            <td class="label">Registration:</td>
            <td>#{{ $receipt->payment->registration_id ?? 'N/A' }}</td>
        </tr>
        @if($receipt->payment->registration?->room_allocation)
        <tr>
            <td class="label">Room:</td>
            <td>{{ $receipt->payment->registration->room_allocation }}</td>
            <td class="label">Invoice:</td>
            <td>{{ $receipt->invoice?->invoice_number ?? 'N/A' }}</td>
        </tr>
        @endif
        @if($receipt->printedBy)
        <tr>
            <td class="label">Printed By:</td>
            <td>{{ $receipt->printedBy->name }}</td>
            <td class="label">Print Count:</td>
            <td>{{ $receipt->print_count + 1 }}</td>
        </tr>
        @endif
    </table>

    @if($receipt->payment?->notes)
    <div style="margin-bottom: 15px; padding: 8px; background: #f8f9fa; border-left: 3px solid #28a745;">
        <strong style="font-size: 9px;">Payment Notes:</strong>
        <p style="margin: 3px 0; font-size: 9px; color: #555;">{{ $receipt->payment->notes }}</p>
    </div>
    @endif

    <div class="footer">
        <p style="margin: 0;">This is an official receipt of payment. Please retain for your records.</p>
        <p style="margin: 2px 0 0 0;">Generated by Brickspoint HMS on {{ now()->format('M d, Y H:i A') }}</p>
    </div>
</body>
</html>
