<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Purchase Order {{ $order->po_number }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #333; }
        .header { text-align: center; border-bottom: 2px solid #1a472a; padding-bottom: 15px; margin-bottom: 20px; }
        .header h1 { color: #1a472a; margin: 0; font-size: 24px; }
        .header p { margin: 5px 0 0; color: #666; }
        .info-table { width: 100%; margin-bottom: 20px; }
        .info-table td { padding: 4px 8px; vertical-align: top; }
        .info-table td:first-child { font-weight: bold; width: 140px; color: #555; }
        .items-table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        .items-table th { background: #1a472a; color: white; padding: 8px; text-align: left; font-size: 11px; }
        .items-table td { padding: 6px 8px; border-bottom: 1px solid #ddd; }
        .items-table tr:nth-child(even) td { background: #f8f9fa; }
        .status-badge { display: inline-block; padding: 4px 12px; border-radius: 12px; font-size: 11px; font-weight: bold; }
        .status-draft { background: #ffc107; color: #333; }
        .status-approved { background: #0d6efd; color: white; }
        .status-received { background: #198754; color: white; }
        .status-cancelled { background: #dc3545; color: white; }
        .footer { text-align: center; color: #999; font-size: 10px; border-top: 1px solid #ddd; padding-top: 10px; margin-top: 30px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>PURCHASE ORDER</h1>
        <p>{{ $order->po_number }}</p>
    </div>

    <table class="info-table">
        <tr><td>Supplier</td><td>{{ $order->supplier->name ?? 'N/A' }}</td></tr>
        <tr><td>Store</td><td>{{ $order->store->name ?? 'N/A' }}</td></tr>
        <tr><td>Status</td><td><span class="status-badge status-{{ $order->status }}">{{ ucfirst($order->status) }}</span></td></tr>
        <tr><td>Created By</td><td>{{ $order->createdBy->name ?? 'N/A' }}</td></tr>
        <tr><td>Created At</td><td>{{ $order->created_at->format('d/m/Y H:i') }}</td></tr>
        @if($order->approved_at)
        <tr><td>Approved At</td><td>{{ \Carbon\Carbon::parse($order->approved_at)->format('d/m/Y H:i') }}</td></tr>
        @endif
        @if($order->notes)
        <tr><td>Notes</td><td>{{ $order->notes }}</td></tr>
        @endif
    </table>

    <table class="items-table">
        <thead>
            <tr>
                <th>Item</th>
                <th>SKU</th>
                <th style="text-align: center;">Quantity</th>
            </tr>
        </thead>
        <tbody>
            @foreach($order->items as $item)
            <tr>
                <td>{{ $item->item->description ?? 'N/A' }}</td>
                <td>{{ $item->item->sku ?? '—' }}</td>
                <td style="text-align: center;">{{ $item->quantity_ordered }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by Brickspoint HMS on {{ now()->format('d/m/Y H:i') }}</p>
    </div>
</body>
</html>
